const API='/api';const titles={dashboard:'Dashboard',models:'Models',benchmarks:'Benchmarks',execute:'Executar',results:'Resultats',compare:'Comparar',ranking:'Rànquing',settings:'Configuració'};let categories=[],models=[],questions=[],currentIndex=0;
const $=s=>document.querySelector(s);async function get(path){const r=await fetch(API+path);if(!r.ok)throw Error(await r.text());return r.json()}
function showPage(p){if(!titles[p])p='dashboard';document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.section===p));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#page-title').textContent=titles[p];location.hash=p;if(p==='models')renderModels();if(p==='benchmarks')renderBenchmarks();if(p==='execute')renderExecute();if(p==='results')renderResults();if(p==='ranking')renderRanking()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page)});window.addEventListener('hashchange',()=>showPage(location.hash.slice(1)));
async function boot(){try{[categories,models,questions]=await Promise.all([get('/categories'),get('/models'),get('/questions')]);$('#status').textContent='● API connectada';renderCategories();renderModels();renderBenchmarks();renderExecute();await renderStats()}catch(e){$('#status').textContent='○ Backend no connectat';renderCategories()}}
function renderCategories(){$('#categories').innerHTML=categories.length?categories.map(c=>`<button class="category-card" data-page="execute" data-category="${c.id}"><strong>${escapeHtml(c.name)}</strong><span>${c.question_count} preguntes</span></button>`).join(''):'<div class="empty">No hi ha categories disponibles.</div>'}
function renderModels(){$('#models-list').innerHTML=models.length?models.map(m=>`<div class="list-item"><b>${escapeHtml(m.name)}</b><span>${escapeHtml(m.provider)} · ${escapeHtml(m.model_id)}${m.context?' · '+m.context+' tokens':''}${m.active?'':' · Inactiu'} <button class="mini" data-delete-model="${m.id}">Eliminar</button></span></div>`).join(''):'<div class="empty">No hi ha models configurats encara.</div>'}
function renderBenchmarks(){$('#benchmark-list').innerHTML=`<div class="list-item"><b>AIBeigmer Core Benchmark</b><span>${categories.length} categories · ${questions.length} preguntes actives · tots els tipus d’avaluació</span></div>`}
function renderExecute(){const cs=$('#exec-category'),ms=$('#exec-model');if(!cs)return;const old=cs.value;cs.innerHTML=categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');if(categories.some(c=>c.id===old))cs.value=old;ms.innerHTML=models.length?models.filter(m=>m.active!==false).map(m=>`<option value="${m.id}">${escapeHtml(m.name)} — ${escapeHtml(m.provider)}</option>`).join(''):'<option value="">Cap model configurat</option>';loadQuestion()}
async function loadQuestion(){const cat=$('#exec-category')?.value;if(!cat)return;try{questions=await get('/questions?category='+encodeURIComponent(cat));currentIndex=Math.min(currentIndex,Math.max(questions.length-1,0));renderCurrentQuestion()}catch{$('#question-box').textContent='No es poden carregar les preguntes.'}}
function renderCurrentQuestion(){const q=questions[currentIndex];$('#question-box').innerHTML=q?`<div class="question-meta"><span>Pregunta ${currentIndex+1}/${questions.length}</span><span>${escapeHtml(q.difficulty)} · ${escapeHtml(q.evaluation_type||'manual_review')}</span></div><b>${escapeHtml(q.title)}</b><p>${escapeHtml(q.question)}</p><small>Requisits: ${escapeHtml((q.requirements||[]).join(' · ')||'Cap')} · Pes ${q.weight??1}</small>`:'No hi ha preguntes actives en aquesta categoria.';const nav=$('#question-nav');if(nav)nav.innerHTML=questions.length?`<button class="secondary" id="prev-question" ${currentIndex===0?'disabled':''}>← Anterior</button><span>${currentIndex+1} / ${questions.length}</span><button class="secondary" id="next-question" ${currentIndex===questions.length-1?'disabled':''}>Següent →</button>`:''}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#exec-category')?.addEventListener('change',()=>{currentIndex=0;loadQuestion()});$('#run-btn')?.addEventListener('click',runExecution);$('#prev-question')?.addEventListener('click',()=>{if(currentIndex>0){currentIndex--;renderCurrentQuestion()}});$('#next-question')?.addEventListener('click',()=>{if(currentIndex<questions.length-1){currentIndex++;renderCurrentQuestion()}});
document.addEventListener('click',async e=>{const b=e.target.closest('#prev-question,#next-question');if(!b)return;if(b.id==='prev-question'&&currentIndex>0)currentIndex--;if(b.id==='next-question'&&currentIndex<questions.length-1)currentIndex++;renderCurrentQuestion();});
async function runExecution(){const q=questions[currentIndex],model=$('#exec-model').value;if(!q||!model)return alert('Selecciona una pregunta i un model.');const btn=$('#run-btn');btn.disabled=true;btn.textContent='⏳ Executant...';$('#execution-result').hidden=true;try{const r=await fetch(API+'/executions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question_id:q.id,model_id:model})});if(!r.ok)throw Error(await r.text());const created=await r.json();const run=await fetch(API+'/executions/'+created.id+'/run',{method:'POST'});if(!run.ok){const t=await run.text();throw Error(t)}const result=await run.json();showExecutionResult(result);await renderResults();await renderStats()}catch(e){alert(e.message||'No s’ha pogut executar la prova.')}finally{btn.disabled=false;btn.textContent='▶ Executar'}}
function showExecutionResult(r){const box=$('#execution-result');box.hidden=false;box.innerHTML=`<b>Resultat de l'execució</b><p><strong>Puntuació:</strong> ${r.score??'—'}/100 · <strong>Temps:</strong> ${r.time_seconds??'—'} s · <strong>Tests:</strong> ${r.tests_passed??'—'}/${r.tests_total??'—'} · <strong>Tokens:</strong> ${r.tokens??'—'}</p><small>${escapeHtml(r.status)} · ${escapeHtml(r.evaluation_type||'manual_review')}</small>${r.response?`<pre>${escapeHtml(r.response)}</pre>`:''}${r.error?`<p class="error">${escapeHtml(r.error)}</p>`:''}`}
async function renderResults(){try{const x=await get('/results');$('#results-list').innerHTML=x.length?x.map(r=>`<div class="list-item"><b>Execució #${r.id}</b><span>${escapeHtml(r.status)} · puntuació ${r.score??'—'} · ${r.time_seconds??'—'}s</span></div>`).join(''):'<div class="empty">Encara no hi ha resultats.</div>'}catch{}}
async function renderStats(){try{const s=await get('/stats');$('#avg-score').textContent=s.average_score??'—';$('#leader').textContent=s.leader??'—';$('#runs').textContent=s.executions??0;$('#fastest').textContent=s.fastest_model??'—'}catch{}}
async function renderRanking(){try{const x=await get('/ranking');$('#ranking-list').innerHTML=x.length?x.map((r,i)=>`<div class="list-item"><b>#${i+1} ${escapeHtml(r.model)}</b><span>${r.score}/100</span></div>`).join(''):'Encara no hi ha resultats puntuables.'}catch{}}
async function addModel(){const name=prompt('Nom del model (ex. GPT-5)');if(!name)return;const provider=prompt('Proveïdor: OpenAI, Google, Anthropic, DeepSeek, OpenRouter o Groq','OpenAI');if(!provider)return;const model_id=prompt('ID exacte del model (ex. gpt-5)');if(!model_id)return;const description=prompt('Descripció','');const context=prompt('Context màxim en tokens (opcional)','');try{const r=await fetch(API+'/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,provider,model_id,description,context:context?Number(context):null,active:true})});if(!r.ok)throw Error(await r.text());models=await get('/models');renderModels();renderExecute();alert('Model afegit correctament. Ja està disponible a Executar.')}catch(e){alert(e.message||'No s’ha pogut afegir el model.')}}
$('#add-model')?.addEventListener('click',addModel);document.addEventListener('click',async e=>{const b=e.target.closest('[data-delete-model]');if(!b)return;if(!confirm('Eliminar aquest model?'))return;const r=await fetch(API+'/models/'+b.dataset.deleteModel,{method:'DELETE'});if(!r.ok)return alert(await r.text());models=await get('/models');renderModels();renderExecute()});
showPage(location.hash.slice(1)||'dashboard');boot();