const API='/api';const titles={dashboard:'Dashboard',models:'Models',benchmarks:'Benchmarks',execute:'Executar',results:'Resultats',compare:'Comparar',ranking:'Rànquing',settings:'Configuració'};let categories=[],models=[],questions=[],currentQuestion=null;
const $=s=>document.querySelector(s);async function get(path){const r=await fetch(API+path);if(!r.ok)throw Error(await r.text());return r.json()}
function showPage(p){if(!titles[p])p='dashboard';document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.section===p));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#page-title').textContent=titles[p];location.hash=p;if(p==='models')renderModels();if(p==='benchmarks')renderBenchmarks();if(p==='execute')renderExecute();if(p==='results')renderResults();if(p==='ranking')renderRanking();if(p==='compare')renderCompare()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page)});window.addEventListener('hashchange',()=>showPage(location.hash.slice(1)));
async function boot(){try{[categories,models,questions]=await Promise.all([get('/categories'),get('/models'),get('/questions')]);$('#status').textContent='● API connectada';renderCategories();renderExecute();renderModels();renderBenchmarks();await renderStats()}catch(e){$('#status').textContent='○ Backend no connectat';renderCategories()}}
function renderCategories(){$('#categories').innerHTML=categories.length?categories.map(c=>`<button class="category-card" data-page="execute" data-category="${c.id}"><strong>${c.name}</strong><span>${c.question_count} preguntes</span></button>`).join(''):'<div class="empty">No hi ha categories disponibles.</div>'}
function renderModels(){$('#models-list').innerHTML=models.length?models.map(m=>`<div class="list-item"><b>${escapeHtml(m.name)}</b><span>${escapeHtml(m.provider)} · ${escapeHtml(m.model_id)}${m.active?'':' · Inactiu'}</span></div>`).join(''):'<div class="empty">No hi ha models configurats encara.</div>'}
function renderBenchmarks(){$('#benchmark-list').innerHTML=`<div class="list-item"><b>AIBeigmer Core Benchmark</b><span>${categories.length} categories · preguntes configurables</span></div>`}
function renderExecute(){const cs=$('#exec-category'),ms=$('#exec-model');if(!cs)return;cs.innerHTML=categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');ms.innerHTML=models.length?models.filter(m=>m.active!==false).map(m=>`<option value="${m.id}">${escapeHtml(m.name)}</option>`).join(''):'<option value="">Cap model configurat</option>';loadQuestion()}
async function loadQuestion(){const cat=$('#exec-category')?.value;if(!cat)return;try{const qs=await get('/questions?category='+encodeURIComponent(cat));questions=qs;currentQuestion=qs[0]||null;renderCurrentQuestion()}catch{$('#question-box').textContent='No es poden carregar les preguntes.'}}
function renderCurrentQuestion(){const q=currentQuestion;$('#question-box').innerHTML=q?`<b>${escapeHtml(q.title)}</b><p>${escapeHtml(q.question)}</p><small>${escapeHtml(q.difficulty)} · ${escapeHtml(q.evaluation_type||'manual_review')} · pes ${q.weight??1}</small>`:'No hi ha preguntes actives en aquesta categoria.'}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#exec-category')?.addEventListener('change',loadQuestion);
$('#run-btn')?.addEventListener('click',runExecution);
async function runExecution(){if(!currentQuestion||!$('#exec-model').value)return alert('Selecciona una pregunta i un model.');const btn=$('#run-btn');btn.disabled=true;btn.textContent='⏳ Executant...';$('#execution-result').hidden=true;try{const r=await fetch(API+'/executions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question_id:currentQuestion.id,model_id:$('#exec-model').value})});if(!r.ok)throw Error(await r.text());const created=await r.json();const run=await fetch(API+'/executions/'+created.id+'/run',{method:'POST'});if(!run.ok)throw Error(await run.text());const result=await run.json();showExecutionResult(result);await renderResults();await renderStats()}catch(e){alert(e.message||'No s’ha pogut executar la prova.')}finally{btn.disabled=false;btn.textContent='▶ Executar'}}
function showExecutionResult(r){const box=$('#execution-result');box.hidden=false;box.innerHTML=`<b>Resultat</b><p><strong>Puntuació:</strong> ${r.score??'—'}/100 · <strong>Temps:</strong> ${r.time_seconds??'—'} s · <strong>Tests:</strong> ${r.tests_passed??'—'}/${r.tests_total??'—'}</p><small>${escapeHtml(r.status)}</small>${r.response?`<pre>${escapeHtml(r.response)}</pre>`:''}${r.error?`<p>${escapeHtml(r.error)}</p>`:''}`}
async function renderResults(){try{const x=await get('/results');$('#results-list').innerHTML=x.length?x.map(r=>`<div class="list-item"><b>Execució #${r.id}</b><span>${escapeHtml(r.status)} · puntuació ${r.score??'—'} · ${r.time_seconds??'—'}s</span></div>`).join(''):'<div class="empty">Encara no hi ha resultats.</div>'}catch{}}
async function renderStats(){try{const s=await get('/stats');$('#avg-score').textContent=s.average_score??'—';$('#leader').textContent=s.leader??'—';$('#runs').textContent=s.executions??0;$('#fastest').textContent=s.fastest_model??'—'}catch{}}
async function renderRanking(){try{const x=await get('/ranking');$('#ranking-list').innerHTML=x.length?x.map((r,i)=>`<div class="list-item"><b>#${i+1} ${escapeHtml(r.model)}</b><span>${r.score}/100</span></div>`).join(''):'Encara no hi ha resultats suficients per crear un rànquing.'}catch{}}
function renderCompare(){$('#compare-list').textContent='Executa proves per generar una comparació real.'}
$('#add-model')?.addEventListener('click',async()=>{const name=prompt('Nom del model (ex. GPT-5)');if(!name)return;const provider=prompt('Proveïdor (OpenAI, Google, Anthropic, DeepSeek, OpenRouter o Groq)','OpenAI');if(!provider)return;const model_id=prompt('ID exacte del model (ex. gpt-5)');if(!model_id)return;const description=prompt('Descripció','');const context=prompt('Context màxim (opcional)','');try{const r=await fetch(API+'/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,provider,model_id,description,context:context?Number(context):null,active:true})});if(!r.ok)throw Error(await r.text());models=await get('/models');renderModels();renderExecute();alert('Model afegit correctament.')}catch(e){alert(e.message||'No s’ha pogut afegir el model.')}});
showPage(location.hash.slice(1)||'dashboard');boot();